name: Get Last Tag
description: Gets the last photon tag.
inputs:
  token:
    description: Github Token
    required: true
  tag:
    description: The current tag to fetch from.
    required: false
    default: LATEST
  owner:
    description: Owner of the Repository
    required: false
    default: PhotonLE
  repository:
    description: Repo name
    required: false
    default: Photon
