name: Builds
on:
  release:
    types: [created]

jobs:
  gma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          coverage: none
      - name: Install Dependencies
        run: composer install -d .github/builder/gma
      - name: Build
        run: php .github/builder/gma/build.php
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '.github/builder/gma/photonle.gma'
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -d
      - name: Build
        run: php .github/builder/update/build.php
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '.github/builder/update/*.html'
