name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: New version ID (eg. v75)

jobs:
  last-tag:
    runs-on: ubuntu-latest
    name: Get Last Tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Current Tag
        run: echo "${{ github.event.inputs.version }}"
      - name: Get Last Tags
        uses: ./.github/get_last_tag
        with:
          owner: JoshPiper
          token: ${{ github.token }}
