name: Build Release

on:
  workflow_dispatch:
    inputs:
#      version:
#        required: true
#        description: New version ID (eg. v75)
      bump:
        required: false
        description: Version type to bump (major / minor)
        default: major

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare Release Data
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install Deps
        run: |
          cd .github/tag_bump && npm i && cd ../..
          cd .github/build_changelogs && npm i && cd ../..
          cd .github/photon_title && npm i && cd ../..
      - name: Get Test Tag Bumping
        id: bump
        uses: ./.github/tag_bump
        with:
          owner: JoshPiper
          token: ${{ github.token }}
          bump: ${{ github.event.inputs.bump }}
      - name: Setup Release Branch
        run: git checkout -b "release/${{ steps.bump.outputs.next }}"
      - name: Write Changelog
        uses: ./.github/build_changelogs
        id: changelog
        with:
          token: ${{ github.token }}
          before: ${{ steps.bump.outputs.last }}
          after: ${{ steps.bump.outputs.next }}
      - name: Generate Series Title
        uses: ./.github/photon_title
        id: title
        with:
          next: ${{ steps.bump.outputs.next }}
      - name: Dump Title Context
        run: echo "$TITLE_CONTEXT"
        env:
          TITLE_CONTEXT: "${{ toJSON( steps.title.outputs ) }}"
      - name: Get Status
        run: git status
      - name: Commit Updated used.json
        run: "git add .github/photon_title/used.json && git commit -m \"chore(release): update used.json\""
      - name: Prepare Updated Photon Config
        run: |
          sed -ie "s/PHOTON_UPDATE = \d+/PHOTON_UPDATE = ${{ steps.bump.outputs.numeric }}/" lua/autorun/photon/sh_emv_config.lua
          sed -ie "s/PHOTON_SERIES = \"[\w .]+\"/PHOTON_SERIES = \"${{ steps.title.outputs.series }}\"/" lua/autorun/photon/sh_emv_config.lua
          git status
      - name: Commit Updated Photon Config
        run: "git add lua/autorun/photon/sh_emv_config.lua && git commit -m \"chore(release): bump photon config version\""
      - name: Prepare Updated Doc-Blocks
        run: sed -i "s/^@release(.*)$/@release ${{ steps.bump.outputs.next }} - ${{ steps.title.outputs.series }}/" lua/**.lua
      - name: Commit Updated Doc-Blocks
        run: "git add lua/**.lua && git commit -m \"chore(release): update version doc-blocks\""
      - name: Push Release Candidate
        run: git push

