name: Build Release

on:
  workflow_dispatch:
    inputs:
#      version:
#        required: true
#        description: New version ID (eg. v75)
      bump:
        required: false
        description: Version type to bump (major / minor)
        default: major

jobs:
  release-data:
    runs-on: ubuntu-latest
    name: Get Release Data
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Deps
        run: |
          cd .github/tag_bump && npm i && cd ../..
          cd .github/build_changelogs && npm i && cd ../..
          cd .github/photon_title && npm i && cd ../..
      - name: Get Test Tag Bumping
        id: bump
        uses: ./.github/tag_bump
        with:
          owner: JoshPiper
          token: ${{ github.token }}
          bump: ${{ github.event.inputs.bump }}
      - name: Setup Release Branch
        run: git checkout -b "release/${{ steps.bump.outputs.next }}"
      - name: Write Changelog
        uses: ./.github/build_changelogs
        id: changelog
        with:
          token: ${{ github.token }}
          before: ${{ steps.bump.outputs.last }}
          after: ${{ steps.bump.outputs.next }}
      - name: Generate Series Title
        uses: ./.github/photon_title
        id: title
        with:
#          next: ${{ steps.bump.outputs.next }}
          next: v110
      - name: Read used.json
        run: cat .github/photon_title/used.json
      - name: Generate Series Title 2
        uses: ./.github/photon_title
        with:
          #          next: ${{ steps.bump.outputs.next }}
          next: v160
      - name: Read used.json
        run: cat .github/photon_title/used.json
      - name: Dump Title Context
        run: echo "$TITLE_CONTEXT"
        env:
          TITLE_CONTEXT: "${{ toJSON( steps.title.outputs ) }}"

