name: Build Release

on:
  workflow_dispatch:
    inputs:
#      version:
#        required: true
#        description: New version ID (eg. v75)
      bump:
        required: false
        description: Version type to bump (major / minor)
        default: major

jobs:
  last-tag:
    runs-on: ubuntu-latest
    name: Get Last Tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Current Tag
        run: echo "${{ github.event.inputs.version }}"
      - name: Install Deps
        run: cd .github/get_last_tag && npm i
      - name: Get Test Tag Bumping
        id: bump
        uses: ./.github/get_last_tag
        with:
          owner: JoshPiper
          token: ${{ github.token }}
          bump: ${{ github.event.inputs.bump }}
      - name: Dump Step Context
        run: echo "$STEP_CONTEXT"
        env:
          STEP_CONTEXT: "${{ toJSON( steps.bump.outputs ) }}"
